== Streams

L'API `Stream<T>` a été introduite par Java 8. Le `Stream` est un objet java qui permet de définir via une API une série de traitements à réaliser sur une collection ou tableau d'objets. Cette API nécessite largement l'utilisation de lambdas et de références de méthodes (que nous verrons plus tard). En revanche, aucune structure de boucle n'est nécessaire pour appliquer ces opérations.

Avec les `Streams`, la programmation java peut devenir déclarative au lieu d'être impérative : déclarer ce que doit faire un traitement et non comment il doit le faire. Dans ce cadre déclaratif, les fonctions sont manipulées comme n'importe quel objet java pour être passées en paramètre ou retournées.

Prenons un exemple :

[source, java]
----
include::src/main/java/com/acme/Declarative.java[tag=declarative]
----
<1> Création d'un `Stream` à partir du tableau.
<2> Filtrage des éléments vide.
<3> Suppression des doublons.
<4> Décompte des éléments restants.

Ce programme ne déclare que les opérations à effectuer. À aucun moment la façon d'exécuter ces traitements n'est définie : pas de boucle, pas de variable locale pour stocker les résultats temporaires, etc.
Le `Stream` est maître des algorithmes à utiliser, de l'optimisation et même de l'ordonnancement des opérations. La documentation de chacune des méthodes du `Stream` précise les garanties qu'elles offrent, charge au développeur de les prendre en compte.

Stream signifie flux : c'est à dire qu'une fois qu'un `Stream` a été utilisé pour appliquer une succession d'opération et a permis d'obtenir un résultat, il n'est plus réutilisable.

L'exemple suivant ne fonctionnera donc pas :

[source, java]
----
include::src/main/java/com/acme/StreamNotReusable.java[tag=no-reusability]
----
<1> icon:bomb[2x,role=red] `Stream` déjà épuisé !

=== Créer un Stream : générateurs de flux
Toute séquence d'éléments peut être transformée en `Stream` :

- Un tableau :

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=generate-from-array-1]
----
- Une Collection :

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=generate-from-collection]
----
- Une suite numérique :

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=generate-from-suite]
----
- Un autre flux :

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=generate-from-stream]
----

- Ou même rien du tout :

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=generate-from-void]
----

=== Appliquer des opérations : méthodes intermédiaires
Les méthodes intermédiaires sont l'ensemble des opérations applicables à un `Stream` et qui renvoient un `Stream`.

Puisqu'elles renvoient un `Stream`, elles peuvent être chaînées pour appliquer plusieurs méthodes intermédiaires successivement.

Ces méthodes utilisent une approche builder, c'est-à-dire que leur invocation permet de créer le pipeline de traitement qui sera _ou pas_ invoqué dans le futur.

[IMPORTANT]
====
Les méthodes intermédiaires ne déclenchent aucune exécution. Elles ne font que configurer une future utilisation.
====

- `distinct` : ne conserve que les éléments non égaux du `Stream` initial.

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=middle-methods-distinct]
----
- `sorted` : Elle prend en paramètre un `Comparator` et trie les éléments selon leur ordre naturel. Il est possible de préciser l'ordre dans lequel les éléments doivent être triés en fournissant un Comparator en entrée.

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=middle-methods-sorted]
----
- `limit` / `skip` : `limit(x)` tronque le `Stream` à x éléments, tandis que `skip(x)` retire du `Stream` les x premiers éléments.

- `filter` : Prend en paramètre un `Predicate` et retire du `Stream` tous les éléments ne le respectant pas.

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=middle-methods-filter]
----
- `map` : Prend en paramètre une `Function` et l'applique sur chacun des éléments du `Stream`. Permet de passer d'un Stream<K> à un Stream<V>.

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=middle-methods-map]
----
`mapToInt`, `mapToDouble` et `mapToLong` sont des spécialisations de map qui imposent que le `Stream` résultant de l'application du map soit respectivement un `IntStream`, `DoubleStream`, `LongStream`. Ces `Streams` permettent de manipuler les types primitifs `int`, `double` et `long`.

- `flatMap` : transforme chaque élément du `Stream` en un autre `Stream` via la fonction passée en paramètre et retourne la concaténation de chacun des `Streams` obtenus.

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=middle-methods-flatmap]
----
Dans l'exemple ci-dessus, `letters` est un `Stream` composé de chacun des caractères présents dans chacun des noms de `names`. Il équivaut à :
[source]
----
Stream<String> names = Stream.of("P","i","e","r","r","e","-","T","o","t","o", "J","e","a","n","-","T","o","t","o", "T","u","t","u", "T","o","t","o");
----
Le `Stream` d'origine n'a donc pas forcément la même cardinalité que le `Stream` résultant du `flatmap`.

- `peek` : Il permet de "jeter un coup d'oeil" sur les éléments du `Stream`, sans les transformer, et sans être final non plus. Dans la grande majorité des cas, si vous apercevez un `peek`, fuyez. La doc indique clairement qu'il s'agit  d'une méthode dédiée au debug. Par ailleurs le peex ne fonctionne que si une opération intermédiaire ou l'opération terminal a besoin de parcourir l'intégralité des éléments.

[source,java]
----
List<String> l = Arrays.asList("A", "B", "C", "D");
     long count = l.stream().peek(item -> System.out.println(item)).count();<1>
----
<1> Le `count` n'a pas besoin de parcourir la liste donc pas de parcours de liste, et donc le peek n'est pas déclenché.





=== Obtenir un résultat : méthodes terminales
Les méthodes terminales sont les méthodes de l'API `Stream` qui ne renvoient pas un `Stream` : elles terminent donc les enchaînements d'opérations sur un `Stream`.

[IMPORTANT]
====
Les méthodes terminales déclenchent l'exécution des traitements configurés via les méthodes intermédiaires, provoquant ainsi l'épuisement du `Stream`.
====


==== Dénombrer
- `count` :
    ** dénombre les éléments présents dans le `Stream`.
    ** type de retour : `long`

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=end-methods-count]
----
==== Réduire
Les méthodes de réduction permettent de passer d'un `Stream` à un unique résultat.

- `allMatch` :
    ** renvoie vrai si tous les éléments du `Stream` respectent le prédicat fourni en paramètre. Faux sinon.
    **  type de retour : `boolean`
- `anyMatch` :
    ** renvoie vrai si au moins un élément du `Stream` respecte le prédicat fourni en paramètre. Faux sinon.
**  type de retour : `boolean`

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=end-methods-anyMatch]
----
- `noneMatch` :
    ** renvoie vrai si aucun élément du `Stream` ne respecte le prédicat fourni en paramètre. Faux sinon.
**  type de retour : `boolean`
- `reduce` :
    ** renvoie un objet qui résulte de l'accumulation de tous les éléments du `Stream` via le BiOperator donné en entrée d
    **  type de retour : `boolean`

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=end-methods-reduce]
----

- `collect` : rassemble tous les éléments du `Stream` dans un nouvel objet, tel qu'une List, une Map ou une String par exemple.
    ** `collect` prend en paramètre un collecteur de type `Collector`. `Collectors` propose plusieurs implémentations usuelles telles que tolist().

[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=end-methods-collect]
----

==== Rechercher
Les méthodes de recherche d'éléments renvoient des `Optional<T>`. Un `Optional` encapsule un objet java (ou du vide) et fournit une API qui permet mettre en place des traitements ne dépendants pas de la nullité de l'objet, sans mettre en place de structure conditionnelle.

Pour un stream de type `Stream<T>` :

- `findAny` :
    ** renvoie n'importe quel élément du `Stream`.
    ** type de retour : `Optional<T>`
- `findFirst`:
    ** renvoie le premier élément du `Stream`
    ** type de retour : `Optional<T>`
- `max`:
    ** renvoie l'élément le plus grand du `Stream`, selon le comparateur passé en paramètre
    ** type de retour : `Optional<T>`
- `min`:
    ** renvoie l'élément le plus petit du `Stream`, selon le comparateur passé en paramètre
    ** type de retour : `Optional<T>`

=== Découpage

Rappelons que les méthodes intermédiaires ne font effectivement aucun traitement. Si l'on doit effectuer de nombreuses transformations, il peut être  plus lisible de scinder le code :
[source, java]
----
include::src/main/java/com/acme/StreamBasics.java[tag=splitting-declaration]
----

