== Streams et Optional

L'API streams est apparue avec Java 8 et se prête très bien à l'utilisation de lambdas et référence de méthode. Un stream est un objet java qui permet de définir une série de traitements à réaliser sur une collection ou tableau d'objets sans structure de boucle, via une api très complète et la manipulation d'expressions lambdas.
La programmation devient déclarative au lieu d'être impérative : déclarer ce que doit faire un traitement et non comment il doit le faire. Dans ce cadre déclaratif, les fonctions sont manipulées comme n'importe quel objet java pour être passées en paramètre ou retournées, d'où l'utilisation des interfaces fonctionnelles.

Prenons un exemple :

[source, java]
----
include::src/main/java/com/acme/Declarative.java[tag=declarative]
----
Ce programme déclare les opérations à effectuer :

- la création d'un stream à partir d'un tableau
- le critère sur lequel filtrer les éléments
- la suppression de doublon
- le décompte d'élements.

A aucun moment la façon d'exécuter ces traitements n'est définie : pas de boucle, pas de variable locale pour stocker les résultats temporaires, etc. Le stream est maître des algorithmes à utiliser, de l'optimisation et même de l'ordonnancement des opérations. La documentation de chacune des méthodes du stream précise les garanties qu'elles offrent, charge au développeur de les prendre en compte.

Stream signifie flux : une fois qu'un stream a été utilisé pour appliquer une succession d'opération et a permis d'obtenir un résultat, il n'est pas réutilisable.

L'exemple suivant ne fonctionnera donc pas :
[source, java]
----
include::src/main/java/com/acme/StreamNotReusable.java[tag=no-reusability]
----

#### Créer un stream : générateurs de flux


#### Appliquer des opérations : méthodes intermédiaires


#### Obtenir un résultat : méthodes terminales


